// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-i61vSXklRbkMuxHnfrkvgwioKLrQ928',
    appId: '1:49590326862:web:3a23b101f8fec06671551f',
    messagingSenderId: '49590326862',
    projectId: 'chapapp-e3b26',
    authDomain: 'chapapp-e3b26.firebaseapp.com',
    storageBucket: 'chapapp-e3b26.appspot.com',
    measurementId: 'G-8SZ5XY20PZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_Gf8bT7ajMb3Xq1Vj2udj-X5cKVfXm0o',
    appId: '1:49590326862:android:6746f2e346b2f99171551f',
    messagingSenderId: '49590326862',
    projectId: 'chapapp-e3b26',
    storageBucket: 'chapapp-e3b26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkYTu4zrc1BBpzfh9uaMTL93-EeT45CFM',
    appId: '1:49590326862:ios:87f9dd5899ea658e71551f',
    messagingSenderId: '49590326862',
    projectId: 'chapapp-e3b26',
    storageBucket: 'chapapp-e3b26.appspot.com',
    iosClientId: '49590326862-kkc0pm449j2vap1ljmscp359b864omk5.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkYTu4zrc1BBpzfh9uaMTL93-EeT45CFM',
    appId: '1:49590326862:ios:87f9dd5899ea658e71551f',
    messagingSenderId: '49590326862',
    projectId: 'chapapp-e3b26',
    storageBucket: 'chapapp-e3b26.appspot.com',
    iosClientId: '49590326862-kkc0pm449j2vap1ljmscp359b864omk5.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
